name = "Model"
uuid = "224c9c6b-c6d8-4a1c-a83c-4244ffc3d9ae"
authors = ["NoFishLikeIan <andreatitton96@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
FastPow = "c0e83750-1142-43a8-81cf-6c956b72b4d1"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
BenchmarkTools = "1.6.0"
FastClosures = "0.3.2"
FastPow = "0.1.0"
LogExpFunctions = "0.3.29"
Revise = "3.8.1"
