name = "Grid"
uuid = "5b109459-d7f8-4d72-be29-a06ad992825f"
authors = ["NoFishLikeIan <andreatitton96@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ZigZagBoomerang = "36347407-b186-4a6a-8c98-4f4567861712"

[compat]
BenchmarkTools = "1.6.0"
Revise = "3.8.1"
